<?php
$students = $block->getSort();
?>

<fieldset class="fieldset">
    <?php
    if (count($students)) {
        ?>
        <div class="table-wrapper custom-data " id="employee_table">
            <table class="data table table-data-items ">
                <caption class="table-caption"><?= $block->escapeHtml('Custom Pagination') ?></caption>
                <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml('ID') ?></th>
                    <th scope="col" class="col name"><?= $block->escapeHtml('Name') ?></th>
                    <th scope="col" class="col gender"><?= $block->escapeHtml('Gender') ?></th>
                    <th scope="col" class="col dob"><?= $block->escapeHtml('Date of birth') ?></th>
                    <th scope="col" class="col action">Action</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($students as $item): ?>
                    <tr>
                        <td data-th="ID" class="col id">
                            <span><?= $block->escapeHtml($item->getEntity_id()) ?></span>
                        </td>
                        <td data-th="Name" class="col name">
                            <span><?= $block->escapeHtml($item->getName()) ?></span>
                        </td>
                        <td data-th="Gender" class="col gender">
                            <?php if ($block->escapeHtml($item->getGender())==0): ?>
                                <span>Male</span>
                            <?php else: ?>
                                <span>Female</span>
                            <?php endif; ?>
                        </td>
                        <td data-th="dob" class="col dob">
                            <span><?= $block->escapeHtml($item->getDob()) ?></span>
                        </td>
                        <td class="col detail">
                            <a  href="<?php echo $block->getUrl('student/index/detail').'?ids='.$item->getEntity_id() ?>">Detail</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom">
                <?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
    <?php } else { ?>
        <div class="message info empty">
            <span><?= $block->escapeHtml('You have no data in table.') ?></span>
        </div>
    <?php  } ?>
</fieldset>

